version: '2'
services:
  db:
    image: postgres:9.6
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /root/pgdata:/var/lib/postgresql/data/pgdata
      - /home/code:/home/code
  web:
    build: .
    container_name: django
    command: /bin/bash /home/code/runserver.sh
    volumes:
      - /home/code:/home/code
    ports:
      - "8000:8000"
    links:
      - db