version: '2'
services:
  db:
    image: postgres:9.6
    container_name: pgsql
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ~/pgdata:/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: /bin/bash ./runserver.sh
    volumes:
      - /home/code:/home/code
    ports:
      - "8000:8000"
    depends_on:
      - db