version: '3'
services:
  db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - E:\projects\waterlawblog\pgdata:/var/lib/postgresql/data/pgdata
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/code/
    ports:
      - "8000:8000"
    depends_on:
      - db