# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 11:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misaka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='消息参数'),
        ),
    ]
