# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-18 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171206_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_name', models.CharField(max_length=30, verbose_name='Github 登录名')),
                ('github_id', models.IntegerField(verbose_name='Github 用户ID')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Github', verbose_name='与用户关联的 Github'),
        ),
    ]
